name: Build Debian Package

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      release:
        description: "JSON encoded list of releases."
        required: false
        type: string

jobs:
  metadata:
    name: Ubuntu supported releases
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.generate-releases.outputs.releases }}
    steps:
      - name: Query Launchpad for supported releases
        id: generate-releases
        run: |
          set -euxo pipefail
          echo -n releases= >> ${GITHUB_OUTPUT}
          curl -s https://api.launchpad.net/devel/ubuntu/series | \
            jq '.entries[] | select(.version >= "22.04" and
                                    (.status == "Supported" or
                                     .status == "Current Stable Release" or
                                     .status == "Active Development" or
                                     .status == "Pre-release Freeze")) |
                .name' | jq -cs | \
            tee -a ${GITHUB_OUTPUT}
          cat ${GITHUB_OUTPUT}

  debian-build:
    needs:
      - metadata
    strategy:
      fail-fast: false
      matrix:
        release: ${{ inputs.release && fromJson(inputs.release) || fromJson(needs.metadata.outputs.releases) }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install build tooling
      run: |
        set -euxo pipefail
        sudo apt-get update
        sudo apt-get install -yq sbuild ubuntu-dev-tools debootstrap lintian devscripts
        sudo usermod -aG sbuild "$USER"

    - name: Install build dependencies
      run: |
        set -euxo pipefail
        sudo mk-build-deps --install --remove --tool='apt-get --yes' debian/control

    - name: Create schroot
      run: |
        set -euxo pipefail
        sg sbuild -c "mk-sbuild --arch=amd64 --name=${{ matrix.release }}-sbuild ${{ matrix.release }}"

    - name: Build source package
      run: |
        set -euxo pipefail
        dpkg-buildpackage -S -us -uc -d

    - name: Build binary package
      run: |
        set -euxo pipefail
        sudo sbuild --arch=amd64 -d ${{ matrix.release }}-sbuild --no-run-lintian ../regress-stack_*.dsc

    - name: Run lintian
      continue-on-error: true
      run: |
        set -euxo pipefail
        lintian --info ../*.changes

    - name: Collect artifacts
      run: |
        set -euxo pipefail
        mkdir -p /tmp/artifacts
        cp ../*.deb ../*.dsc ../*.changes ../*.buildinfo ../*.tar.* /tmp/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: debian-packages-${{ matrix.release }}-${{ github.sha }}
        path: /tmp/artifacts/
