name: Functional Tests

on:
  workflow_call:


jobs:
  functional-tests:
    strategy:
      fail-fast: false
      matrix:
        base: [noble, jammy]
    runs-on: [self-hosted, linux, X64, large, noble]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        set -euxo pipefail
        sudo apt-get update
        sudo apt-get install -yq snapd
        sudo systemctl enable snapd
        sudo systemctl restart snapd
        sudo snap refresh --channel 5.21/stable lxd \
            || sudo snap install --channel 5.21/stable lxd

    - name: Clear FORWARD firewall rules
      run: |
        set -euxo pipefail
        # Docker can inject rules causing firewall conflicts
        sudo iptables -P FORWARD ACCEPT  || true
        sudo ip6tables -P FORWARD ACCEPT || true
        sudo iptables -F FORWARD  || true
        sudo ip6tables -F FORWARD || true

    - name: Configure LXD
      run: |
        set -euxo pipefail
        sudo snap set lxd daemon.group=adm
        sudo lxd init --auto

    - name: Launch instance
      run: |
        set -euxo pipefail
        cat .github/lxd-instance-config.yml | \
          lxc launch ubuntu-daily:${{ matrix.base }} regress-stack \
            --vm -c limits.cpu=6 -c limits.memory=24GiB
        while true; do
          sleep 5
          lxc exec regress-stack -- cloud-init status --wait && break
        done
        lxc file push -r . regress-stack/root/

    - name: Plan
      run: |
        lxc exec regress-stack -- sh -c '
        cd regress-stack/src &&
        sudo python3 -m regress_stack plan'

    - name: Setup
      run: |
        lxc exec regress-stack -- sh -c '
        cd regress-stack/src &&
        sudo python3 -m regress_stack setup'

    - name: Test
      run: |
        lxc exec regress-stack -- sh -c '
        cd regress-stack/src &&
        sudo python3 -m regress_stack test --concurrency auto'
