name: Pull Request

on:
  pull_request:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      run: sudo snap install --classic astral-uv

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --yes dpkg-dev libapt-pkg-dev

    - name: Run unit-tests
      run: uv run py.test
